# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trey Lanzer
author: TexasBullet26
email: lanzertrey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Trey Lanzer and this is my first website! Learn more by
  clicking the about link at the top.

google_analytics: UA-99924733-2

permalink: /:title/
# absoulute_url: http://www.treylanzer.com
baseurl: "" # "/_posts" # the subpath of your site, e.g. /blog
url: "http://www.treylanzer.com" # the base hostname & protocol for your site
twitter_username: TexasBullet26
github_username:  TexasBullet26

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#  - /about.md
#  - /posts.md
#  - /contact.md

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Github metadata settings
repository: TexasBullet26/TexasBullet26.github.io
# End

# jekyll-seo-tag settings
social:
  name: TexasBullet26
  links:
    - https://twitter.com/TexasBullet26
    - https://github.com/TexasBullet26

twitter:
  username: TexasBullet26
# End

defaults:
  -
    scope:
      path: "_layouts/post"
      type: "page" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout
      author: "Trey Lanzer"

# Site menu settings
menu:
  - title: "About"
    url: "/about"
  - title: "My Blog"
    url: "/blog"
  - title: "Contact Me"
    url: "/contact"
